<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a0a2bd23-5950-41dd-8ae8-ef99c717dc7a</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_sql_tutorial</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[3]/a[4]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.ga-nav[href='\/sql\/default\.asp']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'ga-nav') and equals(@title,'SQL Tutorial')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>ga-nav</value>
        <webElementGuid>93e71b5b-de87-4ad0-84a5-3d7cd4ec7558</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>SQL Tutorial</value>
        <webElementGuid>d9f80e00-6b77-4049-8dc1-42fcc644dd9a</webElementGuid>
    </webElementProperties>
</WebElementEntity>